server:
  port: 8888 #服务端口
spring: 
  application:  
    name: configserver #指定服务名
  profiles:
    active: dev
  cloud:  
    config:
      server:
        git: #配置git仓库地址
          uri: https://github.com/haosenwei/property
          username: 961970674@qq.com
          password: hao189108
#  rabbitmq: #RabbitMQ相关的配置
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest

eureka: 
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://localhost:8761/eureka/
  instance: 
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ipAddress: 127.0.0.1
management:
  security:
    enabled: false #是否开启actuator安全认证
#server.port=8888
#spring.cloud.config.server.git.uri=https://github.com/haosenwei/property/blob/master/
#spring.cloud.config.server.git.search-paths=/**
#spring.cloud.config.server.git.username=961970674@qq.com
#spring.cloud.config.server.git.password=hao189108
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#eureka.instance.appname=configserver
#spring.profiles.active=dev
#spring.profiles.lable=dev
#spring.cloud.config.label=master