server:
  port: 8888 #服务端口
spring:
  cloud:
    config:
      server:
        health:
          repositories:
            myservice:
              label: mylabel
            myservice-dev:
              name: myservice
              profiles: development
        git:
          uri: https://github.com/haosenwei/property
          username: 961970674@qq.com
          password: hao189108
eureka:
  instance:
    appname: configserver
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

#server.port=8888
#spring.cloud.config.server.git.uri=https://github.com/haosenwei/property/blob/master/
#spring.cloud.config.server.git.search-paths=/**
#spring.profiles.active=native
#spring.cloud.config.server.native.searchLocations=D:/git/property
#spring.cloud.config.label=master
#spring.cloud.config.server.git.username=961970674@qq.com
#spring.cloud.config.server.git.password=hao189108
#eureka.client.service-url.defaultZone=http://18761.b.bangmc.vip/eureka/