server:
  port: 8081

spring:
  application:
    name: configtest
  profiles:
    active: dev
  cloud:
    config:
      profile: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
