server:
  port: 58081

spring:
  application:
    name: configtest
  profiles:
    active: dev
  cloud:
    config:
      profile: dev
#  rabbitmq: #RabbitMQ相关的配置
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#eureka:
#  client:
#    service-url:
#      defaultZone: http://admin:admin@localhost:8761/eureka/